<a href="https://colab.research.google.com/github/shobhitt013/MachineLearning/blob/main/100daysML_DAY26_LabelOrdinalEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/customer.csv')
df.sample(5)

    age  gender   review education purchased
31   22  Female     Poor    School       Yes
42   30  Female     Good        PG       Yes
44   77  Female  Average        UG        No
20   57  Female  Average    School       Yes
30   73    Male  Average        UG        No

In [ ]:
df = df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
X_train = df.copy()
X_train

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
# Only fit on the first two columns (review and education) to match the categories provided
oe.fit(X_train.iloc[:, :2])

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train.iloc[:, :2] = oe.transform(X_train.iloc[:, :2])
X_train

   review education purchased
0     1.0       0.0        No
1     0.0       1.0        No
2     2.0       2.0        No
3     2.0       2.0        No
4     1.0       1.0        No
5     1.0       0.0       Yes
6     2.0       0.0        No
7     0.0       0.0       Yes
8     1.0       1.0        No
9     2.0       1.0       Yes
10    2.0       1.0       Yes
11    2.0       1.0       Yes
12    0.0       0.0        No
13    1.0       0.0        No
14    0.0       2.0       Yes
15    0.0       1.0        No
16    0.0       1.0       Yes
17    0.0       1.0       Yes
18    2.0       0.0        No
19    0.0       2.0       Yes
20    1.0       0.0       Yes
21    1.0       2.0        No
22    0.0       2.0       Yes
23    2.0       0.0        No
24    1.0       2.0       Yes
25    2.0       0.0        No
26    0.0       2.0        No
27    0.0       2.0        No
28    0.0       0.0        No
29    1.0       1.0       Yes
30    1.0       1.0        No
31    0.0       0.0       Yes
32    1.0       1.0       Yes
33    2.0       2.0       Yes
34    1.0       0.0        No
35    0.0       0.0       Yes
36    2.0       1.0       Yes
37    1.0       2.0       Yes
38    2.0       0.0        No
39    0.0       2.0        No
40    2.0       0.0        No
41    2.0       2.0       Yes
42    2.0       2.0       Yes
43    0.0       2.0        No
44    1.0       1.0        No
45    0.0       2.0       Yes
46    0.0       2.0        No
47    2.0       2.0       Yes
48    2.0       1.0       Yes
49    2.0       1.0        No

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
X_train

   review education purchased
0     1.0       0.0        No
1     0.0       1.0        No
2     2.0       2.0        No
3     2.0       2.0        No
4     1.0       1.0        No
5     1.0       0.0       Yes
6     2.0       0.0        No
7     0.0       0.0       Yes
8     1.0       1.0        No
9     2.0       1.0       Yes
10    2.0       1.0       Yes
11    2.0       1.0       Yes
12    0.0       0.0        No
13    1.0       0.0        No
14    0.0       2.0       Yes
15    0.0       1.0        No
16    0.0       1.0       Yes
17    0.0       1.0       Yes
18    2.0       0.0        No
19    0.0       2.0       Yes
20    1.0       0.0       Yes
21    1.0       2.0        No
22    0.0       2.0       Yes
23    2.0       0.0        No
24    1.0       2.0       Yes
25    2.0       0.0        No
26    0.0       2.0        No
27    0.0       2.0        No
28    0.0       0.0        No
29    1.0       1.0       Yes
30    1.0       1.0        No
31    0.0       0.0       Yes
32    1.0       1.0       Yes
33    2.0       2.0       Yes
34    1.0       0.0        No
35    0.0       0.0       Yes
36    2.0       1.0       Yes
37    1.0       2.0       Yes
38    2.0       0.0        No
39    0.0       2.0        No
40    2.0       0.0        No
41    2.0       2.0       Yes
42    2.0       2.0       Yes
43    0.0       2.0        No
44    1.0       1.0        No
45    0.0       2.0       Yes
46    0.0       2.0        No
47    2.0       2.0       Yes
48    2.0       1.0       Yes
49    2.0       1.0        No

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = X_train['purchased']
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = X_train['purchased']
y_train = le.transform(y_train)
y_train

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])